# Generated by Django 3.2.10 on 2021-12-13 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_space_number', models.PositiveIntegerField(unique=True, verbose_name='Нормер парковочного места')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_parking', models.DateTimeField(verbose_name='Начало бронирования')),
                ('date_finish_parking', models.DateTimeField(verbose_name='Окончание бронирования')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.parkingspace', verbose_name='Парковочное место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь забронированного места')),
            ],
        ),
    ]
